데이터 살펴보기

In [2]:
import pickle
from pathlib import Path
from IPython.display import JSON, display

# 경로 설정
PKL_PATH = Path("../data/light_data.pkl")

with open(PKL_PATH, "rb") as f:
    data = pickle.load(f)

display(JSON(data[0], expanded=True))

In [8]:
from collections import Counter
import pandas as pd

# 설정
TOP_N_AGENTS = 10

# (name, persona) 조합으로 집계
agent_counts = Counter(
    (agent["name"], agent["persona"])
    for episode in data
    for agent in episode["agents"]
)

# 상위 N명
top_agents = pd.DataFrame(
    [
        {
            "name": name,
            "persona": persona,
            "count": count
        }
        for (name, persona), count
        in agent_counts.most_common(TOP_N_AGENTS)
    ]
)

display(top_agents)

       name                                            persona  count
0      king  I am a king of the whole empire. I give rules ...    332
1      king  I am the king. I rule this kingdom alongside m...    291
2    person  The humans walking around. I am one of them. A...    265
3    priest  I am here to help the needy. I am well respect...    230
4   servant  I come from the lower class. I do what I am to...    197
5     queen  I need a new cushion for this throne! All this...    190
6     guard  I am a guard at the royal castle.  I am brave ...    183
7   peasant  I am but a peasant.  The king looks down on us...    165
8     child  I usually go to the park to watch my child pla...    158
9  villager  I live in a very old village on the bad side o...    155

In [9]:
# 상위 agent의 (name, persona) 집합
selected_agents = set(
    zip(top_agents["name"], top_agents["persona"])
)

episode_rows = []

for idx, episode in enumerate(data):

    # 해당 에피소드에 등장하는 (name, persona)
    agents = {
        (agent["name"], agent["persona"])
        for agent in episode["agents"]
    }

    # 모든 등장 agent가 상위 N명에 포함되어야 함
    if agents and agents.issubset(selected_agents):
        episode_rows.append({
            "episode": idx,
            "agents": [agent["name"] for agent in episode["agents"]],
            "setting": episode["setting"]["name"]
        })

selected_episodes = pd.DataFrame(episode_rows)

display(selected_episodes)

     episode            agents                         setting
0       1402   [child, priest]                Temple courtyard
1       1419  [guard, servant]                           Tower
2       1501   [king, servant]              Entrance to castle
3       1626  [queen, servant]                Queen's quarters
4       1632   [king, servant]                 King's chambers
..       ...               ...                             ...
196    10061     [guard, king]                     castle exit
197    10147     [king, queen]                 King's Quarters
198    10195   [king, servant]                      main foyer
199    10216    [king, person]  Torture equipment storage room
200    10243   [king, servant]              Courtyard exterior

[201 rows x 3 columns]